### ISSUE TITLE
Subject duplicated

### ISSUE THREAD

**Issue by NicolaLodato** [lucamaro/robotframework-smtplibrary#1]
Hi,
 emails sent with your library have Subject header duplicated (as you can easily verify in your smtp log).
The issue is on line 308 and following:

            envelope['Subject'] = self.subject

            recipients = self.get_message_recipients()

            envelope['From'] = self.mail_from
            envelope['To'] = COMMASPACE.join(self.mail_to)
            envelope['Cc'] = COMMASPACE.join(self.mail_cc)

            envelope['Subject'] = self.subject

As you can see, there are 2 lines: envelope['Subject'] = self.subject
Can you please correct this issue in next release?

Thnaks

Nicola Lodato

**Comment by lucamaro** [comment]
Hi Nicola,
your issue notification has been fixed in commit [1d58dff5c3b5](https://github.com/lucamaro/robotframework-smtplibrary/commit/1d58dff5c3b5d75ca76a9393dc446b1ad5ae6b65).

Thank you,
Luca
